package:
    name: ecmwf_grib
    version: "1.14.2"

source:
    fn: grib_api-1.14.2.tar.gz
    url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.14.2-Source.tar.gz
    sha1: 78a73ee0b43f2a67eb7102abe48f5275f9ef60ff

build:
    skip: True  # [win]
    number: 0
    detect_binary_files_with_prefix: true

requirements:
    build:
        - python <3
        - numpy x.x
        - jasper

    run:
        - python
        - numpy x.x
        - jasper
        - six

test:
    commands:
        - ls $(grib_info -t) | head -n 2   # prints the test data directory.
    imports:
        - gribapi

about:
    home: https://software.ecmwf.int/wiki/display/GRIB/Home
    license: Apache License, Version 2.0
    summary: The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.
