package:
  name: wera2netcdf
  version: "0.0.1"

source:
  fn: wera2netcdf-0.0.1.tar.gz
  url: https://pypi.python.org/packages/source/w/wera2netcdf/wera2netcdf-0.0.1.tar.gz
  md5: beb3bd457aebe6fa3d3b64cd2d0c0cbf

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pytest
    - pandas
    - netcdf4
    - pygc
    - pytz
    - python-dateutil

  run:
    - python
    - pytest
    - pandas
    - netcdf4
    - pygc
    - pytz
    - python-dateutil

test:
  imports:
    - wera2netcdf
    - wera2netcdf.tests

  requires:
    - pytest

about:
  home: https://github.com/axiom-data-science/wera2netcdf
  license: MIT License
  summary: 'A utility to convert WERA total ASCII files into CF NetCDF files.'
