conda clean --yes --source-cache

"%PYTHON%" waf --check-c-compiler=gcc configure build --prefix="%PREFIX%"
if errorlevel 1 exit 1

"%PYTHON%" waf build
if errorlevel 1 exit 1

"%PYTHON%" waf install
if errorlevel 1 exit 1

copy include\adcp.h %LIBRARY_INC%\ || exit 1
copy include\adcp_old.h %LIBRARY_INC%\ || exit 1
copy include\adcpflag.h %LIBRARY_INC%\ || exit 1
copy include\cal.h %LIBRARY_INC%\ || exit 1
copy include\common.h %LIBRARY_INC%\ || exit 1
copy include\data_id.h %LIBRARY_INC%\ || exit 1
copy include\data_lst.h %LIBRARY_INC%\ || exit 1
copy include\dbdcl.h %LIBRARY_INC%\ || exit 1
copy include\dbedit.h %LIBRARY_INC%\ || exit 1
copy include\dbext.h %LIBRARY_INC%\ || exit 1
copy include\dbglo.h %LIBRARY_INC%\ || exit 1
copy include\dbhost.h %LIBRARY_INC%\ || exit 1
copy include\dbinc.h %LIBRARY_INC%\ || exit 1
copy include\dblscale.h %LIBRARY_INC%\ || exit 1
copy include\dpmask.h %LIBRARY_INC%\ || exit 1
copy include\find_def.h %LIBRARY_INC%\ || exit 1
copy include\geninc.h %LIBRARY_INC%\ || exit 1
copy include\io_.h %LIBRARY_INC%\ || exit 1
copy include\io_nc.h %LIBRARY_INC%\ || exit 1
copy include\ioserv.h %LIBRARY_INC%\ || exit 1
copy include\jdtime.h %LIBRARY_INC%\ || exit 1
copy include\matfile.h %LIBRARY_INC%\ || exit 1
copy include\mc0.h %LIBRARY_INC%\ || exit 1
copy include\mem_.h %LIBRARY_INC%\ || exit 1
copy include\misc.h %LIBRARY_INC%\ || exit 1
copy include\ocean.h %LIBRARY_INC%\ || exit 1
copy include\pos_to_m.h %LIBRARY_INC%\ || exit 1
copy include\posn.h %LIBRARY_INC%\ || exit 1
copy include\profmask.h %LIBRARY_INC%\ || exit 1
copy include\prtarray.h %LIBRARY_INC%\ || exit 1
copy include\prtspecl.h %LIBRARY_INC%\ || exit 1
copy include\prtstruc.h %LIBRARY_INC%\ || exit 1
copy include\readping.h %LIBRARY_INC%\ || exit 1
copy include\scale.h %LIBRARY_INC%\ || exit 1
copy include\sort.h %LIBRARY_INC%\ || exit 1
copy include\time_.h %LIBRARY_INC%\ || exit 1
copy include\unscale.h %LIBRARY_INC%\ || exit 1
copy include\use_adcp.h %LIBRARY_INC%\ || exit 1
copy include\use_db.h %LIBRARY_INC%\ || exit 1
copy include\userbuff.h %LIBRARY_INC%\ || exit 1
copy include\valuelst.h %LIBRARY_INC%\ || exit 1
copy include\vector.h %LIBRARY_INC%\ || exit 1
copy include\vstat.h %LIBRARY_INC%\ || exit 1
copy build\include\config.h %LIBRARY_INC%\ || exit 1

copy build\libcodas3_static.a %LIBRARY_LIB%\ || exit 1
copy build\libcodas3_shared.dll.a %LIBRARY_LIB%\ || exit 1

copy build\codas3_shared.dll %SCRIPTS%\ || exit 1
copy build\util\chtime.exe %SCRIPTS%\ || exit 1
copy build\util\db2todb3.exe %SCRIPTS%\ || exit 1
copy build\util\delblk.exe %SCRIPTS%\ || exit 1
copy build\util\fixnbyte.exe %SCRIPTS%\ || exit 1
copy build\util\lst_prof.exe %SCRIPTS%\ || exit 1
copy build\util\lstblock.exe %SCRIPTS%\ || exit 1
copy build\util\mkblkdir.exe %SCRIPTS%\ || exit 1
copy build\util\showdb.exe %SCRIPTS%\ || exit 1
copy build\util\to_date.exe %SCRIPTS%\ || exit 1
copy build\util\to_day.exe %SCRIPTS%\ || exit 1
copy build\util\to_week.exe %SCRIPTS%\ || exit 1
copy build\util\asc_dump.exe %SCRIPTS%\ || exit 1
copy build\util\chprodid.exe %SCRIPTS%\ || exit 1
copy build\util\ldcodas.exe %SCRIPTS%\ || exit 1
copy build\util\codas_prefix.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\atg.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\bvfreq.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\depth.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\grav.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\press.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\sal78.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\svan.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\svel.exe %SCRIPTS%\ || exit 1
copy build\ocean\cmd\theta.exe %SCRIPTS%\ || exit 1
copy build\grid\llgrid.exe %SCRIPTS%\ || exit 1
copy build\grid\timegrid.exe %SCRIPTS%\ || exit 1
copy build\vecplot\vector.exe %SCRIPTS%\ || exit 1
copy build\vecplot\extract.exe %SCRIPTS%\ || exit 1
copy build\profstat\profstat.exe %SCRIPTS%\ || exit 1
copy build\adcp\adcpsect\adcpsect.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\depthcng.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\depth_change_os.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\badbin.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\unbadbin.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\blkscan.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\botmpas3.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\fix_temp.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\fix_hdg.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\flag.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\getmat.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\last_85.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\logscan.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\set_top.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\updscan.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\dbupdate.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\fillgap.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\newflag.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\setflags.exe %SCRIPTS%\ || exit 1
copy build\adcp\edit\set_lgb.exe %SCRIPTS%\ || exit 1
copy build\adcp\cal\arrdep.exe %SCRIPTS%\ || exit 1
copy build\adcp\cal\refabsbt.exe %SCRIPTS%\ || exit 1
copy build\adcp\cal\timslip.exe %SCRIPTS%\ || exit 1
copy build\adcp\cal\rotate.exe %SCRIPTS%\ || exit 1
copy build\adcp\cal\rotnav.exe %SCRIPTS%\ || exit 1
copy build\adcp\cal\fix_bt_ss_bug.exe %SCRIPTS%\ || exit 1
copy build\adcp\scanload\loadping.exe %SCRIPTS%\ || exit 1
copy build\adcp\scanload\scanping.exe %SCRIPTS%\ || exit 1
copy build\adcp\ping2mat\ping2mat.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\bt2tobt3.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\convadcp.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\convadc2.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\fixunits.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\getnav.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\lst_temp.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\lst_npings.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\lst_hdg.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\pgbin.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\set_bit.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\setpmask.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\lst_conf.exe %SCRIPTS%\ || exit 1
copy build\adcp\util\lst_alfa.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\edfix.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\lst_btrk.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\nav2dir.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\putnav.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\put_txy.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\put_tuv.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\ref2mat.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\refabs.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\sm2mat.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\smoothr.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\ubprint.exe %SCRIPTS%\ || exit 1
copy build\adcp\nav\nmea_gps.exe %SCRIPTS%\ || exit 1
copy build\ctd\load\load_bot.exe %SCRIPTS%\ || exit 1
copy build\ctd\load\load_ctd.exe %SCRIPTS%\ || exit 1
copy build\ctd\load\load_odf.exe %SCRIPTS%\ || exit 1
copy build\ctd\util\conv_ctd.exe %SCRIPTS%\ || exit 1
