package:
    name: pygridtools
    version: "0.2"

source:
    git_url: https://github.com/Geosyntec/pygridtools.git
    git_tag: v0.2

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - gridgen
        - fiona
        - python
        - pandas
        - numpy
        - matplotlib
        - pygridgen

test:
    imports:
        - pygridtools
    commands:
        - nosetests
    requires:
        - nose

about:
    home: https://github.com/Geosyntec/pygridtools.git
    license:  BSD License
    summary: 'Miscellaneous utilities built upon pygridgen'
