{% set version = "1.5.17" %}

package:
  name: shapely
  version: {{ version }}

source:
  fn: Shapely-{{ version }}.tar.gz
  url: https://github.com/Toblerity/Shapely/archive/{{ version }}.tar.gz
  sha256: 85dd42a3e229f434642ad39744ebc82cd352931c6686d858bd9607649b5a4d8a
  patches:
    - geos_c.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - geos 3.4.*
    - cython
    - numpy x.x
    - msinttypes  # [win and py<35]
  run:
    - python
    - geos 3.4.*
    - numpy x.x

test:
  imports:
    - shapely
    - shapely.speedups._speedups
    - shapely.vectorized._vectorized
  commands:
    - conda inspect linkages -p $PREFIX shapely  # [not win]
    - conda inspect objects -p $PREFIX shapely  # [osx]

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD 3-Clause
  summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
