package:
    name: simplejson
    version: "3.8.0"

source:
    fn: simplejson-3.8.0.tar.gz
    url: https://pypi.python.org/packages/source/s/simplejson/simplejson-3.8.0.tar.gz
    md5: 72f3b93a6f9808df81535f79e79565a2

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - simplejson
        - simplejson.tests
        - simplejson._speedups

about:
    home: http://github.com/simplejson/simplejson
    license: MIT License or Academic Free License (AFL)
    summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
