package:
    name: pyhum
    version: 1.3.9

source:
    fn: PyHum-1.3.9.tar.gz
    url: https://pypi.python.org/packages/source/P/PyHum/PyHum-1.3.9.tar.gz
    md5: 6eb6c1d255b6b92c2f8c433ef069528d

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python >=2.7,<3
        - cython
        - numpy x.x
    run:
        - python
        - numpy x.x
        - scipy
        - pillow
        - matplotlib
        - scikit-learn
        - scikit-image
        - pyproj
        - joblib
        - simplekml
        - basemap
        - pyresample
        - dask

test:
    imports:
        - PyHum

about:
    home: https://github.com/dbuscombe-usgs/PyHum
    license: GNU Library or Lesser General Public License (LGPL)
    summary: Python/Cython scripts to read Humminbird DAT

extra:
    recipe-maintainers:
        - ocefpaf
