package:
    name: flopy
    version: "3.1.1"

source:
    git_url: https://github.com/modflowpy/flopy.git
    git_tag: 3.1.1

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy
        - matplotlib
    run:
        - python
        - numpy
        - matplotlib

about:
    home: https://code.google.com/p/flowpy/
    license: BSD
    summary: 'scripts to run MODFLOW, MT3D, SWI and SEAWAT'
