package:
    name: pysgrid
    version: "v0.1.1"

source:
    git_url: https://github.com/sgrid/pysgrid.git
    git_tag: "v0.1.1"

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - netcdf4

test:
    imports:
        - pysgrid

about:
    home: https://github.com/sgrid/pysgrid
    license: BSD
    summary: 'Python package for working with staggered gridded data'
