package:
    name: udunits2
    version: 2.2.20

source:
    fn: v2.2.20.tar.gz
    url: https://github.com/Unidata/UDUNITS-2/archive/v2.2.20.tar.gz
    sha1: a0d30024af16749a4a5ca60133b32735ae52f9e2

build:
    number: 1
    detect_binary_files_with_prefix: true
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - cmake  # [win]
        - automake  # [not win]
        - libtool  # [not win]
        - texinfo  # [not win]
        - expat
    run:
        - expat

test:
    requires:
        # Tests don't really need Python, but conda throws
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    commands:
        - udunits2 -h
        - udunits2 -H meter -W miles
        - conda inspect linkages udunits2 --name _test  # [linux]

about:
    home: http://www.unidata.ucar.edu/software/udunits/
    license: https://github.com/Unidata/UDUNITS-2/blob/master/COPYRIGHT
    summary: The UDUNITS package supports units of physical quantities.

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
        - pelson
