package:
    name: iris
    version: 1.7.4.dev

source:
    git_url: https://github.com/SciTools/iris.git
    git_tag: v1.7.x

build:
    number: 0  # [win]
    number: 0  # [not win]

requirements:
  build:
    - python
    - scipy
    - biggus
    - cartopy >=0.11
    - netcdf4
    - udunits2
    - pyke
    - setuptools
    - libmo_unpack  # [not win]
  run:
    - python
    - scipy
    - biggus
    - cartopy >=0.11
    - matplotlib
    - netcdf4
    - ecmwf_grib >=1.12.1  # [not win]
    - numpy
    - pyke
    - udunits2
    - libmo_unpack  # [not win]

test:
  imports:
        - iris
        # pp is not working yet.
        #- iris.fileformats.pp_packing  # [not win]

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: "Analyse and visualise meteorological and oceanographic data sets."
