package:
    name: iris
    version: "1.8.1"

source:
    git_url: https://github.com/SciTools/iris.git
    git_tag: v1.8.1

build:
    number: 4

requirements:
    build:
        - python >=2.7,<3
        - scipy
        - biggus
        - cartopy
        - netcdf4
        - numpy x.x
        - udunits2
        - pyke
        - setuptools
        - libmo_unpack  # [not win]
    run:
        - python
        - scipy
        - biggus
        - cartopy
        - matplotlib
        - netcdf4
        - ecmwf_grib >=1.12.1  # [not win]
        # There is a numpy C ABI dependency for as long as we have a C extension
        # (pp_packing).
        - numpy x.x
        - numpy
        - pyke
        - udunits2
        - libmo_unpack  # [not win]

test:
  imports:
        - iris
        - iris.fileformats.pp_packing  # [not win]

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: 'Analyse and visualise meteorological and oceanographic data sets'
