package:
  name: seawater
  version: !!str 3.3.2

source:
  fn: seawater-3.3.2.tar.gz
  url: https://pypi.python.org/packages/source/s/seawater/seawater-3.3.2.tar.gz
  md5: d2aa85c5b80f5dde84e0046468609be2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - seawater = seawater:main
    #
    # Would create an entry point called seawater that calls seawater.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - seawater
    - seawater.test

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/seawater/
  license: MIT License
  summary: 'Seawater Library for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
