package:
  name: cartopy
  version: !!str 0.11.2
source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: v0.11.2

requirements:
  build:
    - python
    - six
    - numpy
    - cython
    - proj4
    - geos
    # On OSX We need to effectively pin the geos version to the
    # one used by the specific shapely being targetted (we're letting
    # conda's package solver will deal with that).
    - shapely ==1.4.3.issue177  # [osx]
    # owslib is not a build dependency, but it exists as a recipe and
    # should be built before cartopy for cartopy testing. Obvious-ci
    # should be extended to resolve this issue in the future.
    - owslib
  run:
    - python
    - six
    - mock
    - nose
    - pil
    - owslib
    - numpy
    - proj4
    - shapely ==1.4.3.issue177  # [osx]
    - shapely                   # [not osx]
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'

