package:
    name: pywafo
    version: "0.1.2"

source:
    git_url: https://github.com/ocefpaf/pywafo.git
    git_tag: scipy

build:
    number: 0

requirements:
    build:
        - python >=2.7,<3
        - setuptools
        - numpy
        - cython
    run:
        - python
        - six
        - numpy
        - scipy
        - matplotlib
        - numdifftools

test:
    imports:
        - wafo
        - wafo.covariance
        - wafo.data
        - wafo.spectrum
        - wafo.stats
        - wafo.test
        - wafo.transform
        - wafo.transform.test
    requires:
        - nose

about:
    home: https://github.com/wafo-project/pywafo
    license: GNU General Public License (GPL)
    summary: 'Toolbox for statistical analysis and simulation of random waves and random loads.'
