{% set version = "5.0.5" %}

package:
    name: xz
    version: {{ version }}

source:
    fn:  xz-{{ version }}.tar.bz2
    url: http://tukaani.org/xz/xz-{{ version }}.tar.gz
    sha256: 5dcffe6a3726d23d1711a65288de2e215b4960da5092248ce63c99d50093b93a

build:
    number: 1
    skip: True  # [win]

test:
    commands:
        - xz --help
        - unxz --help
        - lzma --help
        - conda inspect linkages -n _test xz  # [linux]

about:
    home: http://tukaani.org/xz/
    summary: The xz command is a very powerful program for compressing files
    license: LGPL-2.1 and GPL-2.0

extra:
    recipe-maintainers:
        - ocefpaf
