{% set version = "0.2.1" %}

package:
  name: geopandas
  version: {{ version }}

source:
  fn: geopandas-{{ version }}.tar.gz
  url: https://github.com/geopandas/geopandas/archive/v{{ version }}.tar.gz
  sha256: 1e1845acbf6cf8dd2850aec9bfaa92892e462887903e3ea1abb8111e88a41206

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    - python
    - pandas
    - pyproj
    - shapely
    - fiona
    - gdal 2.1.*
    - six
    - rtree
    - descartes
    - matplotlib
    - psycopg2  # [not win]
    - sqlalchemy
    - geopy 1.10.0
    - pysal

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data/test.cpg
    - test_data/test.dbf
    - test_data/test.shp
    - test_data/test.shx
  commands:
    - conda inspect linkages -p $PREFIX geopandas  # [not win]
    - conda inspect objects -p $PREFIX geopandas  # [osx]

about:
  home: http://geopandas.org
  license: BSD 3-clause
  summary: 'Geographic pandas extensions.'

extra:
  recipe-maintainers:
    - ocefpaf
