package:
    name: pyaxiom
    version: "1.0.9"

source:
    fn: pyaxiom-1.0.9.tar.gz
    url: https://pypi.python.org/packages/source/p/pyaxiom/pyaxiom-1.0.9.tar.gz
    md5: 40e2972caeab486f56f58241af2856f5

build:
    number: 0
    entry_points:
        - binner=pyaxiom.netcdf.grids.binner:run

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pytz
        - python-dateutil
        - netcdf4
        - pandas
        - pyncml
        - pynco  # [not win]

test:
    imports:
        - pyaxiom
        - pyaxiom.netcdf
        - pyaxiom.netcdf.grids
        - pyaxiom.netcdf.sensors
        - pyaxiom.tests
    commands:
        - binner --help

about:
    home: https://github.com/axiom-data-science/pyaxiom
    license: MIT License
    summary: 'An ocean data toolkit developed and used by Axiom Data Science'
