package:
  name: isodate
  version: !!str 0.4.9

source:
  fn: isodate-0.4.9.tar.gz
  url: https://pypi.python.org/packages/source/i/isodate/isodate-0.4.9.tar.gz
  md5: dd7399f024637f5e59260f59e6af6af4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - isodate = isodate:main
    #
    # Would create an entry point called isodate that calls isodate.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - isodate.tests
    - isodate

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://cheeseshop.python.org/pypi/isodate
  license: BSD License
  summary: 'An ISO 8601 date/time/duration parser and formatter'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
