package:
    name: udunits2
    version: "2.2.17"

source:
    fn: v2.2.17.tar.gz
    url: https://github.com/Unidata/UDUNITS-2/archive/v2.2.17.tar.gz
    sha1: 3dfb7b1f18e21ac5366127778bbfd50ab5b7cf0a

requirements:
  build:
    - expat  # [win]
  run:
    - expat  # [win]

build:
    number: 0 # [win]
    number: 0 # [not win]
    detect_binary_files_with_prefix: true

test:
    commands:
        - udunits2 -h
        - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  summary: "The UDUNITS package supports units of physical quantities."
