package:
    name: pbr
    version: "1.8.1"

source:
    fn: pbr-1.8.1.tar.gz
    url: https://pypi.python.org/packages/source/p/pbr/pbr-1.8.1.tar.gz
    md5: c8f9285e1a4ca6f9654c529b158baa3a

build:
    number: 0
    preserve_egg_dir: True
    entry_points:
        - pbr = pbr.cmd.main:main

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - pbr
        - pbr.cmd
        - pbr.hooks
        #- pbr.tests
    commands:
        - pbr --help
    requires:
        - coverage >=3.6
        #- discover
        #- fixtures >=1.3.1
        #- hacking <0.11,>=0.10.0
        #- mock >=1.2
        #- python-subunit >=0.0.18
        - six >=1.9.0
        - sphinx !=1.2.0,!=1.3b1,<1.3,>=1.1.2
        #- testrepository >=0.0.18
        #- testresources >=0.2.4
        #- testscenarios >=0.4
        #- testtools >=1.4.0
        - virtualenv

about:
    home: https://launchpad.net/pbr
    license: Apache Software License
    summary: 'Python Build Reasonableness'
