package:
    name: biggus
    version: "0.8.0"

source:
    git_url: https://github.com/rhattersley/biggus
    git_tag: newaxis

build:
    number: 1

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - numpy

about:
    home: https://pypi.python.org/pypi/Biggus
    license: LGPL
    summary: Virtual large arrays and lazy evaluation.
