package:
  name: biggus
  version: !!str 0.7.0

source:
  git_url: https://github.com/SciTools/biggus.git
  git_tag: v0.7.0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - biggus = biggus:main
    #
    # Would create an entry point called biggus that calls biggus.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - biggus.tests
    - biggus

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/SciTools/biggus
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: 'Virtual large arrays and lazy evaluation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
