package:
    name: owslib
    version: "0.8.13"

source:
    git_url: https://github.com/geopython/OWSLib.git
    git_tag: 0.8.13

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - python-dateutil
        - pytz
    run:
        - python
        - python-dateutil
        - pytz

test:
    imports:
        - owslib.coverage
        - owslib.waterml
        - owslib.swe.observation
        - owslib.swe.sensor
        - owslib
        - owslib.feature
        - owslib.swe

about:
    home: https://geopython.github.io/OWSLib
    license: BSD License
    summary: 'OGC Web Service utility library'
