package:
  name: affine
  version: !!str 1.0

source:
  fn: affine-1.0.tar.gz
  url: https://pypi.python.org/packages/source/a/affine/affine-1.0.tar.gz
  md5: 6076a7f052e08d191865c00af0fdad30
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - affine = affine:main
    #
    # Would create an entry point called affine that calls affine.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - affine

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/sgillies/affine
  license:  BSD License
  summary: 'Matrices describing affine transformation of the plane'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
