package:
    name: proj4
    version: "4.9.1"

source:
    fn:  proj-4.9.1.tar.gz
    url: http://download.osgeo.org/proj/proj-4.9.1.tar.gz

build:
    number: 4  # [win]
    number: 2

requirements:
    run:
        # The VS version is important. See # https://github.com/SciTools/conda-recipes-scitools/issues/94.
        - python  # [win]

about:
    home: http://trac.osgeo.org/proj/
    license: MIT
    summary: 'Cartographic projection software'
