{% set version = "0.2.0" %}

package:
  name: mo_pack
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/SciTools/mo_pack/archive/v{{ version }}.tar.gz
  md5: c8dbbabd2a267c1e7457c2f0603e7838

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - numpy x.x
    - setuptools
    - cython
    - libmo_unpack
  run:
    - python
    - numpy x.x
    - libmo_unpack

test:
  imports:
    - mo_pack

about:
  home: https://github.com/SciTools/mo_pack
  license: LGPL-3.0
  summary: 'Python wrapper to libmo_unpack.'

extra:
  recipe-maintainers:
    - ocefpaf
