package:
  name: cligj
  version: !!str 0.1.0

source:
  fn: cligj-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/c/cligj/cligj-0.1.0.tar.gz
  md5: 5b3eb7905aab81418cc3fd4accf57d5f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cligj = cligj:main
    #
    # Would create an entry point called cligj that calls cligj.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - click >=3.0

  run:
    - python
    - click >=3.0

test:
  # Python imports
  imports:
    - cligj

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mapbox/cligj
  license: MIT
  summary: u'Click params for GeoJSON CLI'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
