package:
  name: mysql-python
  version: !!str 1.2.5

source:
  fn: MySQL-python-1.2.5.zip
  url: https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.5.zip
  md5: 654f75b302db6ed8dc5a898c625e030c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mysql-python = mysql-python:main
    #
    # Would create an entry point called mysql-python that calls mysql-python.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/farcepest/MySQLdb1
  license: GNU General Public License (GPL)
  summary: 'Python interface to MySQL'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
