package:
    name: unit_conversion
    version: "2.2"

source:
    git_url: https://github.com/NOAA-ORR-ERD/PyNUCOS.git
    git_tag: v2.2

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - unit_conversion
        - unit_conversion.lat_long
        - unit_conversion.unit_data
        - unit_conversion.unit_conversion

about:
    home: https://github.com/NOAA-ORR-ERD/PyNUCOS
    license: Public Domain
    summary: 'Physical Unit conversions for Oil Spill Response'
