package:
    name: awesome-slugify
    version: "1.6.5"

source:
    fn: awesome-slugify-1.6.5.tar.gz
    url: https://pypi.python.org/packages/source/a/awesome-slugify/awesome-slugify-1.6.5.tar.gz
    md5: 58b9b751b4670e3c221f008dd61348a8


build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - regex
        - unidecode >=0.04.14,<0.05

test:
    imports:
        - slugify

about:
    home: https://github.com/dimka665/awesome-slugify
    license: GNU General Public License v3 (GPLv3)
    summary: 'Python flexible slugify function'
