package:
    name: shapely
    version: 1.5.12

source:
    fn: Shapely-1.5.12.tar.gz
    url: https://pypi.python.org/packages/source/S/Shapely/Shapely-1.5.12.tar.gz
    md5: 928d1fda2db064d82288092ea32ef3a9
    patches:
        - geos_c.win.patch  # [win]
        - osx-geos.patch # [osx]
build:
    number: 1

requirements:
    build:
        - python
        - geos >=3.4
        - cython
        - numpy x.x
        - msinttypes  # [win]
    run:
        - python
        - geos >=3.4
        - numpy x.x

test:
    imports:
        - shapely
        - shapely.speedups._speedups
        - shapely.vectorized._vectorized

about:
    home: https://github.com/Toblerity/Shapely
    license: BSD
    summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane'
