package:
  name: shapely
  version: 1.5.8dev0

source:
  git_url: https://github.com/Toblerity/Shapely.git
  git_tag: 2212deb2105d380345c9b558f8f4c3d3be903496
  patches:
    - geos_c.win.patch      # [win]

build:
  number: 0

requirements:
  build:
    - python
    - geos >=3.4
    - cython
    - numpy
  run:
    - python
    - geos
    - numpy

test:
  imports:
    - shapely
    - shapely.speedups._speedups
    - shapely.vectorized._vectorized

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD
  summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane'
